BASE: ['']
DATA:
  TRAIN_DATA_PATH: "/gscratch/ubicomp/xliu0/data3/mnt/Datasets/SyntheticsPublicDataset/RawData/Train"
  VALID_DATA_PATH: "/gscratch/ubicomp/xliu0/data3/mnt/Datasets/SyntheticsPublicDataset/RawData/Val"
  DATASET: SYNTHETICS
  DO_PREPROCESS: True
  DATA_FORMAT: NDCHW
  PREPROCESS :
    DATA_TYPE: ['Normalized','Standardized']
    LABEL_TYPE : Normalized
    CLIP_LENGTH: 180
    CROP_FACE: False
    LARGE_FACE_BOX: False
    FACE_DETECT: False
    H: 72
    W: 72
DEVICE: cuda:0
NUM_OF_GPU_TRAIN: 2
LOG:
  PATH: runs/exp
MODEL:
  DROP_RATE: 0.2
  NAME: Tscan
  TSCAN:
    FRAME_DEPTH: 20
TRAIN:
  BATCH_SIZE: 8
  EPOCHS: 20
  LR: 0.0001
  MODEL_FILE_NAME: tscan_synthetics.pth