BASE: ['']
DATA:
  FS: 30
  DATASET: SYNTHETICS
  DO_PREPROCESS: True
  DATA_FORMAT: NDCHW
  TEST_DATA_PATH: '/gscratch/ubicomp/xliu0/data3/mnt/Datasets/SyntheticsPublicDataset/RawData/Test/'
  PREPROCESS :
    DATA_TYPE: ['Normalized','Standardized']
    LABEL_TYPE : Normalized
    CLIP_LENGTH: 180
    CROP_FACE: False
    LARGE_FACE_BOX: False
    FACE_DETECT: False
    H: 72
    W: 72
DEVICE: cuda:0
LOG:
  PATH: runs/exp
MODEL:
  DROP_RATE: 0.2
  MODEL_DIR: store_model
  NAME: Tscan
  TSCAN:
    FRAME_DEPTH: 10
INFERENCE:
  BATCH_SIZE: 1
  MODEL_PATH: '/gscratch/ubicomp/xliu0/rPPG-Toolbox/store_model/tscan.pth'
TEST:
  METRICS: ['MAE','RMSE']
